env:
  CODECLIMATE_REPO_TOKEN: 03884e44e7bd728d4eb61fcc6246af1dae130ddf9c275998f013567325cfb31d

language: ruby
rvm:
  - 2.4.0

services:
  - mysql
  - elasticsearch

before_install:
  - mysql -e 'CREATE DATABASE IF NOT EXISTS demo_rails_elasticsearch_test;'

before_script:
  - cp config/database.travis.yml config/database.yml
  - sleep 10

script:
  - bin/rake db:migrate RAILS_ENV=test
  - bin/rake
